In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.__version__

'1.1.0'

Pandas is an numerical open source python library that is built on top of NumPy. Why learning Pandas is important:

Pandas allows you do fast analysis as well as data cleaning and preparation Pandas can work well with data from a wide variety of sources such as; Excel sheet, csv file, sql file or even a webpage

Documentation - https://pandas.pydata.org/pandas-docs/version/0.25.3/

# Pandas Series

Pandas series are one-dimensional labeled array that are capable of holding of data of any type

In [4]:
#creating panda series from list
arr = ['a', 'b', 'c', 2, 'e']
ser_1 = pd.Series(arr)

print (ser_1)

0    a
1    b
2    c
3    2
4    e
dtype: object


In [5]:
type(ser_1)

pandas.core.series.Series

In [6]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [7]:
#creating panda series from array
arr = np.array([10, 20, 30, 40, 50])
ser_2 = pd.Series(arr)

print (ser_2)

0    10
1    20
2    30
3    40
4    50
dtype: int32


In [8]:
#create series with specific indexing
ser_3 = pd.Series(arr, index = ['sarah', 'bob', 'alex', 'den', 'nancy'])

print (ser_3)

sarah    10
bob      20
alex     30
den      40
nancy    50
dtype: int32


In [9]:
ser_3.values

array([10, 20, 30, 40, 50])

In [10]:
ser_3.index

Index(['sarah', 'bob', 'alex', 'den', 'nancy'], dtype='object')

In [11]:
print (ser_3[1:3])

bob     20
alex    30
dtype: int32


In [12]:
print (ser_3[[0, 2, 4]])

sarah    10
alex     30
nancy    50
dtype: int32


In [13]:

print (ser_3[:3])

sarah    10
bob      20
alex     30
dtype: int32


In [14]:
print(' Size:',ser_3.size,'\n',
'Shape:',ser_3.shape,'\n',
'Dimension:',ser_3.ndim,'\n',
'Data type:',ser_3.dtype)

 Size: 5 
 Shape: (5,) 
 Dimension: 1 
 Data type: int32


In [ ]:
# slicing by implicit integer index
data[0:2]

We can access a group of specific indices by including these indices in a list,

In [ ]:
# express indexing
data[['a', 'e']]

Notice that when slicing with an explicit index (i.e., data ['a':'c']), the final index is included in the slice, while when slicing with an implicit index (i.e., data[0:2]), the final index is excluded from the slice. When we slicing through a list (i.e., data [['a', 'e']]), all indices are equally accessed.

Create a series of cities with population as value

what will be index
what will be value

In [16]:

population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)


population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [17]:
population['California']


38332521

In [18]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [19]:
population['Texas':'Florida']

Texas       26448193
New York    19651127
Florida     19552860
dtype: int64

In [20]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [21]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int32


# Create a Pandas DataFrame

Pandas DataFrame is a two-dimensional labeled data structure.

Pandas is a data analysis library that provides a variety of data structures and data manipulation methods that allows to perform complex tasks with simple one-line commands.

In the following sections, we will be working on the Pandas library and its uses. We will be reviewing how the objects are defined by pandas, operating their values and executing a series of important operations for data analysis. 

Let us begin!

In [22]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [23]:
pet_info = [['Blain', 10, 'Dog'], ['Lucy', 4 , 'Cat'], ['Cinco', 8, 'Rabbit']]
pet_info

[['Blain', 10, 'Dog'], ['Lucy', 4, 'Cat'], ['Cinco', 8, 'Rabbit']]

In [24]:
pet_df = pd.DataFrame(pet_info, columns = ['Name', 'Age', 'Type'])
                     
pet_df
#,index = ['A', 'B', 'C']

Name  Age    Type
0  Blain   10     Dog
1   Lucy    4     Cat
2  Cinco    8  Rabbit

In [25]:
pet_df['Age']

0    10
1     4
2     8
Name: Age, dtype: int64

In [26]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [27]:
states.columns

Index(['population', 'area'], dtype='object')

Thus the DataFrame can be thought of as a generalization of a two-dimensional NumPy array, where both the rows and columns have a generalized index for accessing the data.

There are some functions and attributes that allow us to observe basic information about the data stored in a DataFrame object:

DataFrame.head() -> returns the content of the first 5 rows, by default

DataFrame.tail() -> returns the content of the last 5 rows, by default

DataFrame.shape -> returns a tuple of the form (num_rows, num_columns)

DataFrame.columns -> returns the name of the columns

DataFrame.index -> returns the index of the rows


Using `data.head ()` and `data.tail ()` we can see the content of the data. Unless otherwise specified, DataFrame and Series objects have indexes starting from 0 and incrementing monotonically and incrementally as integers.

In [28]:
states['area'] # Accessing the 'area' column of the data DataFrame

#states.area # Equivalent to data['area']


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [29]:
states['population'] # Accessing the 'pop' column of the data DataFrame


California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [30]:
data = states.copy()

In [31]:
type(data)

pandas.core.frame.DataFrame

In [32]:
data

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [33]:
data['density'] = data['population']/data['area']
data

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [34]:
data.values

array([[3.83325210e+07, 4.23967000e+05, 9.04139261e+01],
       [2.64481930e+07, 6.95662000e+05, 3.80187404e+01],
       [1.96511270e+07, 1.41297000e+05, 1.39076746e+02],
       [1.95528600e+07, 1.70312000e+05, 1.14806121e+02],
       [1.28821350e+07, 1.49995000e+05, 8.58837628e+01]])

In [46]:
states.shape

(5, 2)

In [ ]:
data = states.copy() #copy a dataframe

# Iris Dataset

In [77]:
from sklearn.datasets import load_iris
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [78]:
data = iris.data
column_names = iris.feature_names

In [79]:
column_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [81]:
type(data)

numpy.ndarray

In [ ]:
data[2:5]

In [ ]:
data[0:10:2] #intervals

In [56]:
df = pd.DataFrame(data, columns = column_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [58]:
df.shape

(150, 4)

In [59]:
df.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

In [62]:
df.tail(20)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [63]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [67]:
df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [68]:
df['sepal length (cm)'].mean()


5.843333333333334